module.exports = {
	"advanced-markdown-editor": {
		"identifier": "org.example.advanced-markdown-editor",
		"name": "Advanced Markdown",
		"content_type": "SN|Component",
		"area": "editor-editor",
		"version": "",
		"description": "A fully featured Markdown editor that supports live preview, a styling toolbar, and split pane support.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/advanced-markdown",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/adv-markdown.jpg"
	},
	"simple-markdown-editor": {
		"identifier": "org.example.simple-markdown-editor",
		"name": "Simple Markdown",
		"content_type": "SN|Component",
		"area": "editor-editor",
		"version": "",
		"description": "A Markdown editor with dynamic split-pane preview.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/simple-markdown",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/simple-markdown.jpg"
	},
	"plus-editor": {
		"identifier": "org.example.plus-editor",
		"name": "Plus Editor",
		"content_type": "SN|Component",
		"area": "editor-editor",
		"version": "",
		"description": "From highlighting to custom font sizes and colors, to tables and lists, this editor is perfect for crafting any document. (Converts your note to an HTML format.)",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/plus-editor",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/plus-editor.jpg"
	},
	"fancy-markdown-editor": {
		"identifier": "org.example.fancy-markdown-editor",
		"name": "Fancy Markdown Editor",
		"content_type": "SN|Component",
		"area": "editor-editor",
		"version": "",
		"description": "A beautiful split-pane Markdown editor with synced-scroll and LaTeX support.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/fancy-markdown-editor",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/fancy-markdown.jpg"
	},
	"minimal-markdown-editor": {
		"identifier": "org.example.minimal-markdown-editor",
		"name": "Minimal Markdown",
		"content_type": "SN|Component",
		"area": "editor-editor",
		"version": "",
		"description": "A minimal Markdown editor with inline style support.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/minimal-markdown",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/min-markdown.jpg"
	},
	"code-editor": {
		"identifier": "org.example.code-editor",
		"name": "Code Editor",
		"content_type": "SN|Component",
		"area": "editor-editor",
		"version": "",
		"description": "Syntax highlighting and convenient keyboard shortcuts for over 120 programming languages. Ideal for code snippets and procedures.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/code-editor",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/code.jpg"
	},
	"vim-editor": {
		"identifier": "org.example.vim-editor",
		"name": "Vim Editor",
		"content_type": "SN|Component",
		"area": "editor-editor",
		"version": "",
		"description": "A code editor with Vim key bindings.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/vim-editor",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/vim.jpg"
	},
	"simple-task-editor": {
		"identifier": "org.example.simple-task-editor",
		"name": "Simple Task Editor",
		"content_type": "SN|Component",
		"area": "editor-editor",
		"version": "",
		"description": "A great way to manage short-term and long-term to-do's. You can mark tasks as completed, change their order, and edit the text naturally in place.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/simple-task-editor",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/task-editor.jpg"
	},
	"autocomplete-tags": {
		"identifier": "org.example.autocomplete-tags",
		"name": "Quick Tags",
		"content_type": "SN|Component",
		"area": "note-tags",
		"version": "",
		"description": "Work more efficiently by quickly selecting from a live list of tags while you type. Supports keyboard shortcuts and folders.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/quick-tags",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/components/autocomplete.jpg"
	},
	"action-bar": {
		"identifier": "org.example.action-bar",
		"name": "Action Bar",
		"content_type": "SN|Component",
		"area": "editor-stack",
		"version": "",
		"description": "Useful utility bar with information about the current note as well as actions like duplicate, copy, and save",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/action-bar",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/components/action-bar.jpg"
	},
	"github-push": {
		"identifier": "org.example.github-push",
		"name": "GitHub Push",
		"content_type": "SN|Component",
		"area": "editor-stack",
		"version": "",
		"description": "Push note changes to a public or private GitHub repository, with options for file extension and commit message.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/github-push",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/components/github-push.jpg"
	},
	"folders-component": {
		"identifier": "org.example.folders-component",
		"name": "Folders",
		"content_type": "SN|Component",
		"area": "tags-list",
		"version": "",
		"description": "Create nested folders from your tags with easy drag and drop. Folders also supports Smart Tags, which allow you to build custom filters for viewing your notes.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/folders",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/components/folders.jpg"
	},
	"midnight-theme": {
		"identifier": "org.example.midnight-theme",
		"name": "Midnight Theme",
		"content_type": "SN|Component",
		"area": "themes",
		"version": "",
		"description": "Elegant utilitarianism.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/midnight",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/themes/midnight-with-mobile.jpg"
	},
	"focus-theme": {
		"identifier": "org.example.focus-theme",
		"name": "Focused Theme",
		"content_type": "SN|Component",
		"area": "themes",
		"version": "",
		"description": "For when you need to go in.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/focused",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/themes/focus-with-mobile.jpg"
	},
	"futura-theme": {
		"identifier": "org.example.futura-theme",
		"name": "Futura Theme",
		"content_type": "SN|Component",
		"area": "themes",
		"version": "",
		"description": "Calm and relaxed. Take some time off.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/futura",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/themes/futura-with-mobile.jpg"
	},
	"titanium-theme": {
		"identifier": "org.example.titanium-theme",
		"name": "Titanium Theme",
		"content_type": "SN|Component",
		"area": "themes",
		"version": "",
		"description": "Light on the eyes, heavy on the spirit.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/titanium",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/themes/titanium-with-mobile.jpg"
	},
	"solarized-dark-theme": {
		"identifier": "org.example.solarized-dark-theme",
		"name": "Solarized Dark Theme",
		"content_type": "SN|Component",
		"area": "themes",
		"version": "",
		"description": "The perfect theme for any time.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/solarized-dark",
		"thumbnail_url": "https://s3.amazonaws.com/standard-notes/screenshots/models/themes/solarized-dark.jpg"
	},
	"dynamic-theme": {
		"identifier": "org.example.dynamic-theme",
		"name": "Dynamic Theme",
		"content_type": "SN|Component",
		"area": "themes",
		"version": "",
		"description": "A smart theme that minimizes the tags and notes panels when they are not in use.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/dynamic",
		"thumbnail_url": ""
	},
	"no-distraction-theme": {
		"identifier": "org.example.no-distraction-theme",
		"name": "No Distraction Theme",
		"content_type": "SN|Component",
		"area": "themes",
		"version": "",
		"description": "A distraction-free writing environment for high levels of clarity and focus.",
		"url": "",
		"download_url": "",
		"latest_url": "",
		"marketing_url": "https://standardnotes.org/extensions/no-distraction",
		"thumbnail_url": ""
	}
};
